using System.Text;
using ScreepsDotNet.Backend.Http.Rendering;

namespace ScreepsDotNet.Backend.Http.Tests.Rendering;

public sealed class BadgeSvgGeneratorTests
{
    private readonly BadgeSvgGenerator _generator = new();

    [Fact]
    public void GenerateSvg_WithNumericType_ReturnsSvg()
    {
        var badge = new
        {
            color1 = "#112233",
            color2 = "#445566",
            color3 = "#778899",
            type = 1,
            param = 0,
            flip = true
        };

        var svg = _generator.GenerateSvg(badge, includeBorder: false);

        Assert.Contains("clip-path=\"url(#clip)\"", svg);
        Assert.Contains("fill=\"#112233\"", svg);
        Assert.Contains("rotate(0", svg);
        Assert.Contains("path d=\"M 50", svg);
    }

    [Fact]
    public void GenerateSvg_WithBorder_RendersCircle()
    {
        var badge = new
        {
            color1 = "#000000",
            color2 = "#111111",
            color3 = "#222222",
            type = 2,
            param = 50,
            flip = false
        };

        var svg = _generator.GenerateSvg(badge, includeBorder: true);

        Assert.Contains("stroke-width=\"5\"", svg);
        Assert.Contains("r=\"47.5\"", svg);
    }

    [Fact]
    public void GenerateSvg_WithCustomPaths_UsesPaths()
    {
        var badge = new
        {
            color1 = "#123456",
            color2 = "#654321",
            color3 = "#abcdef",
            type = new
            {
                path1 = "M 0 0 L 50 50 Z",
                path2 = "M 50 50 L 100 100 Z"
            },
            param = 0
        };

        var svg = _generator.GenerateSvg(badge, includeBorder: false);

        Assert.Contains("M 0 0 L 50 50 Z", svg);
        Assert.Contains("M 50 50 L 100 100 Z", svg);
    }

    [Fact]
    public void GenerateSvg_InvalidData_ReturnsEmptySvg()
    {
        var svg = _generator.GenerateSvg(new { }, includeBorder: false);

        Assert.Equal("<svg xmlns=\"http://www.w3.org/2000/svg\"></svg>", svg);
    }

    [Fact]
    public void Export_BadgeSamples_ToFiles()
    {
        var outputDirectory = Path.Combine(AppContext.BaseDirectory, "BadgeSnapshots");
        Directory.CreateDirectory(outputDirectory);

        var galleryBuilder = new StringBuilder();
        galleryBuilder.AppendLine("<!DOCTYPE html>");
        galleryBuilder.AppendLine("<html lang=\"en\"><head><meta charset=\"utf-8\"/>");
        galleryBuilder.AppendLine("<title>Badge Gallery</title>");
        galleryBuilder.AppendLine("<style>");
        galleryBuilder.AppendLine("body{font-family:Segoe UI,Arial,sans-serif;background:#111;color:#eee;margin:0;padding:20px;}");
        galleryBuilder.AppendLine(".gallery{display:flex;flex-wrap:wrap;gap:16px;}");
        galleryBuilder.AppendLine(".badge{background:#1c1c1c;border:1px solid #333;border-radius:8px;padding:12px;text-align:center;}");
        galleryBuilder.AppendLine(".badge svg{width:96px;height:96px;display:block;margin:0 auto;}");
        galleryBuilder.AppendLine(".label{margin-bottom:8px;font-size:14px;letter-spacing:0.05em;text-transform:uppercase;color:#ccc;}");
        galleryBuilder.AppendLine("</style></head><body>");
        galleryBuilder.AppendLine("<h1>Screeps Badge Gallery</h1>");
        galleryBuilder.AppendLine("<p>Generated by the .NET badge renderer for quick visual inspection.</p>");
        galleryBuilder.AppendLine("<div class=\"gallery\">");

        for (var type = 1; type <= 24; type++)
        {
            var badge = new
            {
                color1 = type % 30,
                color2 = (type + 5) % 30,
                color3 = (type + 10) % 30,
                type,
                param = type % 50 - 25,
                flip = type % 3 == 0
            };

            var svg = _generator.GenerateSvg(badge, includeBorder: true);
            galleryBuilder.AppendLine("<div class=\"badge\">");
            galleryBuilder.AppendLine($"<div class=\"label\">Type {type:00}</div>");
            galleryBuilder.AppendLine(svg);
            galleryBuilder.AppendLine("</div>");
        }

        var customBadge = new
        {
            color1 = "#123456",
            color2 = "#abcdef",
            color3 = "#fedcba",
            type = new
            {
                path1 = "M 10 10 L 90 10 L 90 90 L 10 90 Z",
                path2 = "M 30 30 L 70 30 L 70 70 L 30 70 Z"
            },
            param = 0
        };

        var customSvg = _generator.GenerateSvg(customBadge, includeBorder: false);
        galleryBuilder.AppendLine("<div class=\"badge\">");
        galleryBuilder.AppendLine("<div class=\"label\">Custom</div>");
        galleryBuilder.AppendLine(customSvg);
        galleryBuilder.AppendLine("</div>");

        galleryBuilder.AppendLine("</div></body></html>");

        var galleryFile = Path.Combine(outputDirectory, "BadgeGallery.html");
        File.WriteAllText(galleryFile, galleryBuilder.ToString());
        Assert.True(File.Exists(galleryFile));
    }
}
