using System.Text;
using ScreepsDotNet.Backend.Http.Rendering;

namespace ScreepsDotNet.Backend.Http.Tests.Rendering;

public sealed class BadgeSvgGeneratorTests
{
    private readonly BadgeSvgGenerator _generator = new();

    [Fact]
    public void GenerateSvg_WithNumericType_ReturnsSvg()
    {
        var badge = new
        {
            color1 = "#112233",
            color2 = "#445566",
            color3 = "#778899",
            type = 1,
            param = 0,
            flip = true
        };

        var svg = _generator.GenerateSvg(badge, includeBorder: false);

        Assert.Contains("clip-path=\"url(#clip)\"", svg);
        Assert.Contains("fill=\"#112233\"", svg);
        Assert.Contains("rotate(0", svg);
        Assert.Contains("path d=\"M 50", svg);
    }

    [Fact]
    public void GenerateSvg_WithBorder_RendersCircle()
    {
        var badge = new
        {
            color1 = "#000000",
            color2 = "#111111",
            color3 = "#222222",
            type = 2,
            param = 50,
            flip = false
        };

        var svg = _generator.GenerateSvg(badge, includeBorder: true);

        Assert.Contains("stroke-width=\"5\"", svg);
        Assert.Contains("r=\"47.5\"", svg);
    }

    [Fact]
    public void GenerateSvg_WithCustomPaths_UsesPaths()
    {
        var badge = new
        {
            color1 = "#123456",
            color2 = "#654321",
            color3 = "#abcdef",
            type = new
            {
                path1 = "M 0 0 L 50 50 Z",
                path2 = "M 50 50 L 100 100 Z"
            },
            param = 0
        };

        var svg = _generator.GenerateSvg(badge, includeBorder: false);

        Assert.Contains("M 0 0 L 50 50 Z", svg);
        Assert.Contains("M 50 50 L 100 100 Z", svg);
    }

    [Fact]
    public void GenerateSvg_InvalidData_ReturnsEmptySvg()
    {
        var svg = _generator.GenerateSvg(new { }, includeBorder: false);

        Assert.Equal("<svg xmlns=\"http://www.w3.org/2000/svg\"></svg>", svg);
    }

    [Fact]
    public void Export_BadgeSamples_ToDocsMarkdown()
    {
        var projectRoot = FindRepositoryRoot();
        var docsDir = Path.Combine(projectRoot, "docs", "badges");
        Directory.CreateDirectory(docsDir);

        var markdownBuilder = new StringBuilder();
        markdownBuilder.AppendLine("# Badge Gallery");
        markdownBuilder.AppendLine();
        markdownBuilder.AppendLine("Auto-generated by running:");
        markdownBuilder.AppendLine("```bash");
        markdownBuilder.AppendLine("dotnet test --filter BadgeSvgGeneratorTests.Export_BadgeSamples_ToDocsMarkdown");
        markdownBuilder.AppendLine("```");
        markdownBuilder.AppendLine();
        markdownBuilder.AppendLine("| Type | SVG |");
        markdownBuilder.AppendLine("|------|-----|");

        for (var type = 1; type <= 24; type++)
        {
            var badge = new
            {
                color1 = type % 30,
                color2 = (type + 5) % 30,
                color3 = (type + 10) % 30,
                type,
                param = type % 50 - 25,
                flip = type % 3 == 0
            };

            var svg = _generator.GenerateSvg(badge, includeBorder: true);
            var inline = svg.Replace("\n", string.Empty);
            markdownBuilder.AppendLine($"| Type {type:00} | {inline} |");
        }

        var customBadge = new
        {
            color1 = "#123456",
            color2 = "#abcdef",
            color3 = "#fedcba",
            type = new
            {
                path1 = "M 10 10 L 90 10 L 90 90 L 10 90 Z",
                path2 = "M 30 30 L 70 30 L 70 70 L 30 70 Z"
            },
            param = 0
        };

        var customSvg = _generator.GenerateSvg(customBadge, includeBorder: false).Replace("\n", string.Empty);
        markdownBuilder.AppendLine($"| Custom | {customSvg} |");

        var outputFile = Path.Combine(docsDir, "BadgeGallery.md");
        File.WriteAllText(outputFile, markdownBuilder.ToString());
        Assert.True(File.Exists(outputFile));
    }

    private static string FindRepositoryRoot()
    {
        var current = new DirectoryInfo(AppContext.BaseDirectory);
        while (current is not null && !File.Exists(Path.Combine(current.FullName, "ScreepsDotNet.slnx")))
        {
            current = current.Parent;
        }

        if (current is null)
            throw new DirectoryNotFoundException("Could not locate repository root.");

        return current.FullName;
    }
}
