namespace ScreepsDotNet.Backend.Core.Intents;

using System;
using System.Collections.Generic;

public enum IntentFieldType
{
    ScalarString,
    ScalarNumber,
    ScalarBoolean,
    Price,
    StringArray,
    NumberArray,
    BodyPartArray,
    UserString,
    UserText
}

public sealed record IntentDefinition(string Name, IReadOnlyDictionary<string, IntentFieldType> Fields);

public static class IntentSchemas
{
    public static IReadOnlyDictionary<string, IntentDefinition> All { get; } = CreateSchemas();

    private static IReadOnlyDictionary<string, IntentDefinition> CreateSchemas()
    {
        var comparer = StringComparer.Ordinal;
        return new Dictionary<string, IntentDefinition>(comparer)
        {
            ["notify"] = Create("notify",
                ("message", IntentFieldType.UserText),
                ("groupInterval", IntentFieldType.ScalarNumber)),
            ["createConstructionSite"] = Create("createConstructionSite",
                ("roomName", IntentFieldType.ScalarString),
                ("x", IntentFieldType.ScalarNumber),
                ("y", IntentFieldType.ScalarNumber),
                ("structureType", IntentFieldType.ScalarString),
                ("name", IntentFieldType.UserString)),
            ["createFlag"] = Create("createFlag",
                ("roomName", IntentFieldType.ScalarString),
                ("x", IntentFieldType.ScalarNumber),
                ("y", IntentFieldType.ScalarNumber),
                ("name", IntentFieldType.UserString),
                ("color", IntentFieldType.ScalarNumber),
                ("secondaryColor", IntentFieldType.ScalarNumber)),
            ["destroyStructure"] = Create("destroyStructure",
                ("roomName", IntentFieldType.ScalarString),
                ("id", IntentFieldType.ScalarString)),
            ["removeConstructionSite"] = Create("removeConstructionSite",
                ("roomName", IntentFieldType.ScalarString),
                ("id", IntentFieldType.ScalarString)),
            ["removeFlag"] = Create("removeFlag",
                ("roomName", IntentFieldType.ScalarString),
                ("name", IntentFieldType.UserString)),
            ["cancelOrder"] = Create("cancelOrder",
                ("orderId", IntentFieldType.ScalarString)),
            ["changeOrderPrice"] = Create("changeOrderPrice",
                ("orderId", IntentFieldType.ScalarString),
                ("newPrice", IntentFieldType.Price)),
            ["createOrder"] = Create("createOrder",
                ("type", IntentFieldType.ScalarString),
                ("resourceType", IntentFieldType.ScalarString),
                ("price", IntentFieldType.Price),
                ("totalAmount", IntentFieldType.ScalarNumber),
                ("roomName", IntentFieldType.ScalarString)),
            ["createPowerCreep"] = Create("createPowerCreep",
                ("name", IntentFieldType.UserString),
                ("className", IntentFieldType.ScalarString)),
            ["deal"] = Create("deal",
                ("orderId", IntentFieldType.ScalarString),
                ("amount", IntentFieldType.ScalarNumber),
                ("targetRoomName", IntentFieldType.ScalarString)),
            ["deletePowerCreep"] = Create("deletePowerCreep",
                ("id", IntentFieldType.ScalarString),
                ("cancel", IntentFieldType.ScalarBoolean)),
            ["extendOrder"] = Create("extendOrder",
                ("orderId", IntentFieldType.ScalarString),
                ("addAmount", IntentFieldType.ScalarNumber)),
            ["renamePowerCreep"] = Create("renamePowerCreep",
                ("id", IntentFieldType.ScalarString),
                ("name", IntentFieldType.UserString)),
            ["spawnPowerCreep"] = Create("spawnPowerCreep",
                ("id", IntentFieldType.ScalarString),
                ("name", IntentFieldType.UserString)),
            ["suicidePowerCreep"] = Create("suicidePowerCreep",
                ("id", IntentFieldType.ScalarString)),
            ["upgradePowerCreep"] = Create("upgradePowerCreep",
                ("id", IntentFieldType.ScalarString),
                ("power", IntentFieldType.ScalarNumber)),
            ["activateSafeMode"] = Create("activateSafeMode"),
            ["attack"] = Create("attack",
                ("id", IntentFieldType.ScalarString),
                ("x", IntentFieldType.ScalarNumber),
                ("y", IntentFieldType.ScalarNumber)),
            ["attackController"] = Create("attackController",
                ("id", IntentFieldType.ScalarString)),
            ["boostCreep"] = Create("boostCreep",
                ("id", IntentFieldType.ScalarString),
                ("bodyPartsCount", IntentFieldType.ScalarNumber)),
            ["build"] = Create("build",
                ("id", IntentFieldType.ScalarString),
                ("x", IntentFieldType.ScalarNumber),
                ("y", IntentFieldType.ScalarNumber)),
            ["cancelSpawning"] = Create("cancelSpawning"),
            ["claimController"] = Create("claimController",
                ("id", IntentFieldType.ScalarString)),
            ["createCreep"] = Create("createCreep",
                ("name", IntentFieldType.UserString),
                ("body", IntentFieldType.BodyPartArray),
                ("energyStructures", IntentFieldType.StringArray),
                ("directions", IntentFieldType.NumberArray)),
            ["destroy"] = Create("destroy"),
            ["dismantle"] = Create("dismantle",
                ("id", IntentFieldType.ScalarString)),
            ["drop"] = Create("drop",
                ("amount", IntentFieldType.ScalarNumber),
                ("resourceType", IntentFieldType.ScalarString)),
            ["enableRoom"] = Create("enableRoom",
                ("id", IntentFieldType.ScalarString)),
            ["generateSafeMode"] = Create("generateSafeMode",
                ("id", IntentFieldType.ScalarString)),
            ["harvest"] = Create("harvest",
                ("id", IntentFieldType.ScalarString)),
            ["heal"] = Create("heal",
                ("id", IntentFieldType.ScalarString),
                ("x", IntentFieldType.ScalarNumber),
                ("y", IntentFieldType.ScalarNumber)),
            ["launchNuke"] = Create("launchNuke",
                ("x", IntentFieldType.ScalarNumber),
                ("y", IntentFieldType.ScalarNumber),
                ("roomName", IntentFieldType.ScalarString)),
            ["move"] = Create("move",
                ("id", IntentFieldType.ScalarString),
                ("direction", IntentFieldType.ScalarNumber)),
            ["notifyWhenAttacked"] = Create("notifyWhenAttacked",
                ("enabled", IntentFieldType.ScalarBoolean)),
            ["observeRoom"] = Create("observeRoom",
                ("roomName", IntentFieldType.ScalarString)),
            ["pickup"] = Create("pickup",
                ("id", IntentFieldType.ScalarString)),
            ["processPower"] = Create("processPower"),
            ["produce"] = Create("produce",
                ("resourceType", IntentFieldType.ScalarString),
                ("amount", IntentFieldType.ScalarNumber)),
            ["pull"] = Create("pull",
                ("id", IntentFieldType.ScalarString)),
            ["rangedAttack"] = Create("rangedAttack",
                ("id", IntentFieldType.ScalarString)),
            ["rangedHeal"] = Create("rangedHeal",
                ("id", IntentFieldType.ScalarString)),
            ["rangedMassAttack"] = Create("rangedMassAttack"),
            ["recycleCreep"] = Create("recycleCreep",
                ("id", IntentFieldType.ScalarString)),
            ["renew"] = Create("renew",
                ("id", IntentFieldType.ScalarString)),
            ["renewCreep"] = Create("renewCreep",
                ("id", IntentFieldType.ScalarString)),
            ["reverseReaction"] = Create("reverseReaction",
                ("lab1", IntentFieldType.ScalarString),
                ("lab2", IntentFieldType.ScalarString)),
            ["runReaction"] = Create("runReaction",
                ("lab1", IntentFieldType.ScalarString),
                ("lab2", IntentFieldType.ScalarString)),
            ["remove"] = Create("remove"),
            ["repair"] = Create("repair",
                ("id", IntentFieldType.ScalarString),
                ("x", IntentFieldType.ScalarNumber),
                ("y", IntentFieldType.ScalarNumber)),
            ["reserveController"] = Create("reserveController",
                ("id", IntentFieldType.ScalarString)),
            ["say"] = Create("say",
                ("message", IntentFieldType.UserString),
                ("isPublic", IntentFieldType.ScalarBoolean)),
            ["send"] = Create("send",
                ("targetRoomName", IntentFieldType.ScalarString),
                ("resourceType", IntentFieldType.ScalarString),
                ("amount", IntentFieldType.ScalarNumber),
                ("description", IntentFieldType.UserString)),
            ["setColor"] = Create("setColor",
                ("color", IntentFieldType.ScalarNumber),
                ("secondaryColor", IntentFieldType.ScalarNumber)),
            ["setPosition"] = Create("setPosition",
                ("x", IntentFieldType.ScalarNumber),
                ("y", IntentFieldType.ScalarNumber),
                ("roomName", IntentFieldType.ScalarString)),
            ["setPublic"] = Create("setPublic",
                ("isPublic", IntentFieldType.ScalarBoolean)),
            ["setSpawnDirections"] = Create("setSpawnDirections",
                ("directions", IntentFieldType.NumberArray)),
            ["signController"] = Create("signController",
                ("id", IntentFieldType.ScalarString),
                ("sign", IntentFieldType.UserString)),
            ["suicide"] = Create("suicide"),
            ["transfer"] = Create("transfer",
                ("id", IntentFieldType.ScalarString),
                ("amount", IntentFieldType.ScalarNumber),
                ("resourceType", IntentFieldType.ScalarString)),
            ["unboostCreep"] = Create("unboostCreep",
                ("id", IntentFieldType.ScalarString)),
            ["unclaim"] = Create("unclaim"),
            ["upgradeController"] = Create("upgradeController",
                ("id", IntentFieldType.ScalarString)),
            ["usePower"] = Create("usePower",
                ("power", IntentFieldType.ScalarNumber),
                ("id", IntentFieldType.ScalarString)),
            ["withdraw"] = Create("withdraw",
                ("id", IntentFieldType.ScalarString),
                ("amount", IntentFieldType.ScalarNumber),
                ("resourceType", IntentFieldType.ScalarString))
        };
    }

    private static IntentDefinition Create(string name, params (string Field, IntentFieldType Type)[] fields)
    {
        var comparer = StringComparer.Ordinal;
        var dictionary = new Dictionary<string, IntentFieldType>(comparer);
        foreach (var (field, type) in fields)
            dictionary[field] = type;
        return new IntentDefinition(name, dictionary);
    }
}
