@ScreepsDotNet_Backend_Http_HostAddress = http://localhost:5210

### Health
GET {{ScreepsDotNet_Backend_Http_HostAddress}}/health
Accept: application/json

### Version
GET {{ScreepsDotNet_Backend_Http_HostAddress}}/api/version
Accept: application/json

### Auth - Steam Ticket
POST {{ScreepsDotNet_Backend_Http_HostAddress}}/api/auth/steam-ticket
Content-Type: application/json
Accept: application/json

{
  "ticket": "dev-ticket",
  "useNativeAuth": false
}

### Auth - Me
GET {{ScreepsDotNet_Backend_Http_HostAddress}}/api/auth/me
Accept: application/json
X-Token: {{$dotenv token}}

###
