@ScreepsDotNet_Backend_Http_HostAddress = http://localhost:5210
@ScreepsDotNet_User_Token = dev-ticket-token

### User - World Start Room (protected)
GET {{ScreepsDotNet_Backend_Http_HostAddress}}/api/user/world-start-room
X-Token: {{ScreepsDotNet_User_Token}}
Accept: application/json

### User - World Status (protected)
GET {{ScreepsDotNet_Backend_Http_HostAddress}}/api/user/world-status
X-Token: {{ScreepsDotNet_User_Token}}
Accept: application/json

### User - Respawn Prohibited Rooms (protected)
GET {{ScreepsDotNet_Backend_Http_HostAddress}}/api/user/respawn-prohibited-rooms
X-Token: {{ScreepsDotNet_User_Token}}
Accept: application/json

### User - Branches (protected)
GET {{ScreepsDotNet_Backend_Http_HostAddress}}/api/user/branches
X-Token: {{ScreepsDotNet_User_Token}}
Accept: application/json

### User - Code (protected)
GET {{ScreepsDotNet_Backend_Http_HostAddress}}/api/user/code?branch=default
X-Token: {{ScreepsDotNet_User_Token}}
Accept: application/json

### User - Find (public)
GET {{ScreepsDotNet_Backend_Http_HostAddress}}/api/user/find?username=TestUser
Accept: application/json

### User - Rooms (public)
GET {{ScreepsDotNet_Backend_Http_HostAddress}}/api/user/rooms?id=test-user
Accept: application/json

### User - Stats (public)
GET {{ScreepsDotNet_Backend_Http_HostAddress}}/api/user/stats?interval=8
Accept: application/json

### User - Badge SVG (public)
GET {{ScreepsDotNet_Backend_Http_HostAddress}}/api/user/badge-svg?username=TestUser&border=1
Accept: image/svg+xml

### User - Notify Preferences (protected)
POST {{ScreepsDotNet_Backend_Http_HostAddress}}/api/user/notify-prefs
X-Token: {{ScreepsDotNet_User_Token}}
Content-Type: application/json
Accept: application/json

{
  "disabled": true,
  "interval": 60,
  "errorsInterval": 60
}
