using System.Text;
using ScreepsDotNet.Backend.Http.Rendering;

namespace ScreepsDotNet.Backend.Http.Tests.Rendering.Helpers;

internal static class BadgeGalleryMarkdownBuilder
{
    private const string GenerationCommand = "dotnet test --filter BadgeSvgGeneratorTests.Export_BadgeSamples_ToDocsMarkdown";
    private const string TitleHeading = "# Badge Gallery";
    private const string AutoGeneratedLine = "Auto-generated by running:";
    private const string CodeFence = "```bash";
    private const string TableHeader = "| Type | SVG |";
    private const string TableSeparator = "|------|-----|";

    public static string Build(BadgeSvgGenerator generator, IEnumerable<BadgeSample> numericSamples, BadgeSample customSample)
    {
        var builder = new StringBuilder();
        builder.AppendLine(TitleHeading);
        builder.AppendLine();
        builder.AppendLine(AutoGeneratedLine);
        builder.AppendLine(CodeFence);
        builder.AppendLine(GenerationCommand);
        builder.AppendLine(CodeFence);
        builder.AppendLine();
        builder.AppendLine(TableHeader);
        builder.AppendLine(TableSeparator);

        foreach (var sample in numericSamples)
            AppendSampleRow(builder, generator, sample);

        AppendSampleRow(builder, generator, customSample);
        return builder.ToString();
    }

    private static void AppendSampleRow(StringBuilder builder, BadgeSvgGenerator generator, BadgeSample sample)
    {
        var svg = generator.GenerateSvg(sample.Payload, sample.IncludeBorder);
        var inlineSvg = svg.Replace("\r", string.Empty).Replace("\n", string.Empty);
        builder.AppendLine($"| {sample.Label} | {inlineSvg} |");
    }
}
