namespace ScreepsDotNet.Driver.Constants;

/// <summary>
/// Field names present in intent BSON documents generated by runners.
/// </summary>
public static class IntentDocumentFields
{
    public static class Spawn
    {
        public const string CreateCreep = "createCreep";
        public const string RenewCreep = "renewCreep";
        public const string RecycleCreep = "recycleCreep";
        public const string SetSpawnDirections = "setSpawnDirections";
        public const string CancelSpawning = "cancelSpawning";

        public const string Name = "name";
        public const string Body = "body";
        public const string Directions = "directions";
        public const string EnergyStructures = "energyStructures";
    }

    public static class Movement
    {
        public const string X = "x";
        public const string Y = "y";
    }
}
